import type { Project } from "../types";

/**
 * Project record, Arabic. Mirrors en/projects.ts slug-for-slug, tier-for-tier
 * and data-shape-for-data-shape. Company/person names in `parties`, image
 * paths/dimensions, slugs and sourcePage are locale-invariant and repeated
 * verbatim from the English record; every other field is a professional
 * Arabic rendering of the same, verified source facts.
 */
export const projects: Project[] = [
  // ---------------------------------------------------------------- FLAGSHIP
  {
    slug: "jeddah-tower",
    title: "برج جدة",
    shortTitle: "برج جدة",
    location: "جدة، المملكة العربية السعودية",
    sector: "الأبراج العالية",
    sectorSlug: "high-rise",
    tier: "flagship",
    sourcePage: 11,
    overview:
      "من المخطط أن يرتفع برج جدة لأكثر من 1,000 متر، ليكون وجهة متعددة الاستخدامات بمساحة 245,000 متر مربع، تضم مكاتب، وفندق فور سيزونز بـ200 غرفة، و121 شقة فندقية، و360 وحدة سكنية.",
    verifiedRole:
      "مخططات تنفيذ إنشائية وتنسيق متعدد التخصصات، شملت أكثر من 6,000 مخطط، وخدمات التصميم الإنشائي، وجداول تشكيل الحديد، والكميات، والمنشآت المؤقتة، والدعم الهندسي في موقع العمل.",
    data: [
      { value: "1,000+ m", label: "الارتفاع المخطط" },
      { value: "245,000 sqm", label: "إجمالي المساحة الطابقية" },
    ],
    parties: {
      owner: "Jeddah Economic City (JEC)",
      contractor: "Saudi Binladin Group / ABCD",
      consultant: "Dar Al-Handasah (Shair and Partners)",
    },
    image: {
      src: "/projects/jeddah-tower.webp",
      alt: "تصور فني لبرج جدة يُظهر الشكل المتدرج فائق الارتفاع فوق التطوير المحيط على الواجهة البحرية",
      caption: "تصور المشروع / الملف التعريفي المصدري",
      width: 580,
      height: 820,
    },
    capabilities: ["structural-design-shop-drawings", "construction-management-supervision"],
  },
  {
    slug: "king-abdulaziz-international-airport",
    title: "مطار الملك عبدالعزيز الدولي",
    shortTitle: "مطار الملك عبدالعزيز الدولي",
    location: "جدة، المملكة العربية السعودية",
    sector: "الطيران",
    sectorSlug: "aviation",
    tier: "flagship",
    sourcePage: 12,
    overview:
      "يضم تطوير المطار مرافق للرحلات الداخلية والدولية ورجال الأعمال، مدعومة بـ96 جسرًا هوائيًا، بطاقة استيعابية أولية مخططة تبلغ نحو 30 مليون مسافر.",
    verifiedRole:
      "مكتب فني في الموقع، ومعايير رسم إنشائي بالحاسوب، ومخططات تنفيذ، وتوثيق تنفيذ فعلي عبر الصالات ومراكز الأحمال ومواقف السيارات متعددة الطوابق ومرافق الإطفاء والإنقاذ.",
    data: [
      { value: "670,000 sqm", label: "مساحة التطوير" },
      { value: "82", label: "الصالات" },
      { value: "30m passengers", label: "الطاقة الاستيعابية للمرحلة الأولى" },
    ],
    parties: {
      owner: "General Authority of Civil Aviation (GACA)",
      contractor: "Saudi Binladin Group / ABCD",
      consultant: "Dar Al-Handasah Consulting Engineers",
    },
    image: {
      src: "/projects/kaia-terminal.webp",
      alt: "الواجهة الخارجية لمبنى صالات مطار الملك عبدالعزيز الدولي",
      caption: "نظرة عامة على المطار / الملف التعريفي المصدري",
      width: 699,
      height: 410,
    },
    capabilities: ["structural-design-shop-drawings", "construction-management-supervision"],
    relatedAssignment: {
      slug: "king-abdulaziz-international-airport-surveying",
      label: "المهمة ب — المساحة / الرصد الواقعي",
    },
  },
  {
    slug: "king-abdulaziz-international-airport-surveying",
    title: "مطار الملك عبدالعزيز الدولي — أعمال المساحة",
    shortTitle: "مطار الملك عبدالعزيز — المساحة",
    location: "جدة، المملكة العربية السعودية",
    sector: "الطيران",
    sectorSlug: "aviation",
    tier: "flagship",
    sourcePage: 13,
    overview: "مهمة مساحية ضمن بيئة مشروع مطار الملك عبدالعزيز الدولي.",
    verifiedRole:
      "دعم المسح الطبوغرافي وإعداد خطوط الكنتور والمسح الضوئي ثلاثي الأبعاد معلومات موقع منسّقة وسجلات مكانية.",
    data: [],
    parties: {
      owner: "General Authority of Civil Aviation (GACA)",
      contractor: "Saudi Binladin Group / ABCD",
      consultant: "Dar Al-Handasah Consulting Engineers",
    },
    image: {
      src: "/projects/kaia-surveying.webp",
      alt: "صور مسحية وسجلات موقعية من بيئة مطار الملك عبدالعزيز الدولي",
      caption: "صورة المشروع / الملف التعريفي المصدري",
      width: 637,
      height: 271,
    },
    capabilities: ["civil-infrastructure-surveying"],
    relatedAssignment: {
      slug: "king-abdulaziz-international-airport",
      label: "المهمة أ — المكتب الفني / التنفيذ الإنشائي",
    },
  },
  {
    slug: "king-saud-university-endowment",
    title: "مشروع وقف جامعة الملك سعود",
    shortTitle: "مشروع وقف جامعة الملك سعود",
    location: "الرياض، المملكة العربية السعودية",
    sector: "مؤسسي / استخدام مختلط",
    sectorSlug: "institutional",
    tier: "flagship",
    sourcePage: 14,
    overview:
      "يضم المشروع أحد عشر مبنى وبرجًا، منها مركز مؤتمرات، ومركز تسوق، وفندق فاخر، ومركز طبي، وأجنحة فندقية، ومبانٍ إدارية، بمساحة بناء إجمالية تقارب 680,000 متر مربع.",
    verifiedRole:
      "عمل فريق هندسي مع المقاول واستشاري المشروع على إعداد مخططات التنفيذ الإنشائية.",
    data: [
      { value: "11", label: "المباني والأبراج" },
      { value: "680,000 sqm", label: "مساحة البناء" },
    ],
    parties: {
      owner: "King Saud University — Business Sector",
      contractor: "Saudi Binladin Group / RPD",
      consultant: "Saudi Diyar Consults",
    },
    capabilities: ["structural-design-shop-drawings"],
  },
  {
    slug: "north-jeddah-wastewater-pumping-station",
    title: "محطة ضخ مياه الصرف الصحي شمال جدة",
    shortTitle: "محطة ضخ الصرف الصحي شمال جدة",
    location: "جدة، المملكة العربية السعودية",
    sector: "البنية التحتية",
    sectorSlug: "infrastructure",
    tier: "flagship",
    sourcePage: 15,
    overview:
      "مشروع رئيسي لمياه الصرف الصحي يخدم جدة، ويضم آبار ضخ بقطر يقارب 40 مترًا وعمق 70 مترًا، إلى جانب مبانٍ مساندة وأعمال موقع.",
    verifiedRole:
      "قدّم مكتب فني في الموقع دعم التصميم الإنشائي والمعماري، وتقييم التصميم، ومخططات تنفيذ تفصيلية، ومعلومات التنفيذ الفعلي. وشملت المهمة أكثر من 3,000 مخطط، وجداول تشكيل الحديد، والكميات.",
    data: [{ value: "3,000+", label: "المخططات" }],
    parties: {
      owner: "National Water Company",
      contractor: "Abuljadayel Contracting & Maintenance Ltd. Co.",
      consultant: "Safege-P2mberlin Consortium",
    },
    image: {
      src: "/projects/north-jeddah-wwps.webp",
      alt: "أعمال إنشاء محطة ضخ مياه الصرف الصحي شمال جدة",
      caption: "صورة المشروع / الملف التعريفي المصدري",
      width: 470,
      height: 383,
    },
    capabilities: ["structural-design-shop-drawings", "civil-infrastructure-surveying"],
  },
  {
    slug: "almarai-cpp3",
    title: "مصنع المراعي CPP3 للمعالجة المركزية",
    shortTitle: "مصنع المراعي CPP3",
    location: "الخرج، المملكة العربية السعودية",
    sector: "الصناعي",
    sectorSlug: "industrial",
    tier: "flagship",
    sourcePage: 16,
    overview: "CPP3 مصنع معالجة مركزية صناعي طُوِّر لصالح المراعي.",
    verifiedRole:
      "نُسّقت نماذج تصميم تفصيلية للخرسانة المسلحة والصلب وتقارير الحسابات مع المتطلبات المعمارية والميكانيكية، إلى جانب مخططات التنفيذ الإنشائية وجداول تشكيل الحديد.",
    data: [],
    parties: { owner: "Almarai Company", contractor: "OCC Weavers Ltd." },
    image: {
      src: "/projects/almarai-cpp3.webp",
      alt: "منشأة مصنع المراعي CPP3 للمعالجة المركزية",
      caption: "صورة المشروع / الملف التعريفي المصدري",
      width: 674,
      height: 373,
    },
    capabilities: ["structural-design-shop-drawings"],
  },
  {
    slug: "fakeeh-madina-hospital",
    title: "مستشفى فقيه بالمدينة المنورة",
    shortTitle: "مستشفى فقيه بالمدينة المنورة",
    location: "المدينة المنورة، المملكة العربية السعودية",
    sector: "الرعاية الصحية",
    sectorSlug: "healthcare",
    tier: "flagship",
    sourcePage: 17,
    overview:
      "مقترح لتحويل مبنى فندقي قائم إلى مستشفى بمساحة تقارب 65,000 متر مربع، و200 سرير للمرضى الداخليين، ومرافق سريرية متخصصة.",
    verifiedRole:
      "قيّمت مراجعة نظيرة مستقلة متعددة التخصصات إعادة التصميم مقابل المبادئ والمعايير الهندسية عبر الحزم المعمارية والإنشائية والكهربائية والميكانيكية.",
    data: [
      { value: "65,000 sqm", label: "المساحة التقريبية" },
      { value: "200", label: "أسرّة المرضى الداخليين" },
    ],
    parties: {
      owner: "Dr. Soliman Fakeeh Hospital",
      designer: "DAR Engineering",
      consultant: "Z.A.K Engineering Consultants",
    },
    image: {
      src: "/projects/fakeeh-madina-hospital.webp",
      alt: "الواجهة الخارجية لمبنى مستشفى فقيه بالمدينة المنورة",
      caption: "صورة المشروع / الملف التعريفي المصدري",
      width: 955,
      height: 540,
    },
    capabilities: ["value-engineering", "mep-bim-coordination"],
  },

  // ---------------------------------------------------------------- SELECTED
  {
    slug: "hafez-building",
    title: "مبنى حافظ",
    shortTitle: "مبنى حافظ",
    location: "جدة، المملكة العربية السعودية",
    sector: "هندسة القيمة",
    sectorSlug: "commercial",
    tier: "selected",
    sourcePage: 18,
    overview: "مشروع مبنى تجاري في جدة.",
    verifiedRole:
      "مراجعة تصميم ركّزت على القيمة الإنشائية، مدعومة بمخططات تنفيذ تفصيلية، وفحص، وضبط جودة.",
    data: [],
    parties: {
      owner: "Diyarkom",
      contractor: "Ishada Contracting & Maintenance Ltd. Co.",
      consultant: "KAOS",
    },
    capabilities: ["value-engineering", "structural-design-shop-drawings"],
  },
  {
    slug: "alrassam-twin-towers",
    title: "برجا الرسام التوأم",
    shortTitle: "برجا الرسام التوأم",
    location: "جدة، المملكة العربية السعودية",
    sector: "الأبراج العالية",
    sectorSlug: "high-rise",
    tier: "selected",
    sourcePage: 19,
    overview: "مشروع برجين توأمين جرى دعمه من خلال تنفيذ الهندسة الإنشائية.",
    verifiedRole:
      "هندسة القيمة، ونماذج تصميم الخرسانة المسلحة والصلب، والحسابات، والمخططات المنسّقة، والكميات، طُوِّرت حول الوظيفة والموثوقية وضبط التكلفة.",
    data: [],
    parties: {
      owner: "Mr. Saad AlRassam",
      contractor: "CPC Holding Company",
      consultant: "Buruoj Engineering Consultant",
    },
    image: {
      src: "/projects/alrassam-twin-towers.webp",
      alt: "مشروع برجي الرسام التوأم",
      caption: "صورة المشروع / الملف التعريفي المصدري",
      width: 317,
      height: 301,
    },
    capabilities: ["value-engineering", "structural-design-shop-drawings"],
  },
  {
    slug: "galleria-plaza",
    title: "غاليريا بلازا",
    shortTitle: "غاليريا بلازا",
    location: "جدة، المملكة العربية السعودية",
    sector: "استخدام مختلط / تقييم",
    sectorSlug: "commercial",
    tier: "selected",
    sourcePage: 20,
    overview:
      "يصف المصدر مشروعًا للضيافة والتجزئة في جدة يضم أكثر من 400 غرفة فندقية ومركز تسوق.",
    verifiedRole:
      "استرشدت أعمال تقوية البلاطات الخرسانية القائمة بمسح إنشائي ميداني، وتقييم للترخيم، ومراجعة تصميم.",
    data: [
      { value: "400+", label: "الغرف الفندقية" },
      { value: "9,000 sqm", label: "مساحة التجزئة" },
    ],
    parties: {
      owner: "SEDCO Holding",
      contractor: "United Constructors Contracting Company (UCCL)",
      consultant: "Kling Consult",
    },
    capabilities: ["value-engineering", "civil-infrastructure-surveying"],
  },
  {
    slug: "the-hotel-galleria",
    title: "ذا هوتيل غاليريا",
    shortTitle: "ذا هوتيل غاليريا",
    location: "جدة، المملكة العربية السعودية",
    sector: "استخدام مختلط / تنفيذ",
    sectorSlug: "hospitality",
    tier: "selected",
    sourcePage: 21,
    overview:
      "يصف المصدر مشروعًا للضيافة والتجزئة في جدة يضم أكثر من 400 غرفة فندقية ومركز تسوق.",
    verifiedRole:
      "دعم فريق هندسي المقاول واستشاري المشروع بمخططات تنفيذ إنشائية متوافقة مع برنامج المشروع.",
    data: [
      { value: "400+", label: "الغرف الفندقية" },
      { value: "9,000 sqm", label: "مساحة التجزئة" },
    ],
    parties: {
      owner: "SEDCO Holding",
      contractor: "United Constructors Contracting Company (UCCL)",
      consultant: "Kling Consult",
    },
    image: {
      src: "/projects/hotel-galleria.webp",
      alt: "مشروع ذا هوتيل غاليريا للضيافة والتجزئة",
      caption: "صورة المشروع / الملف التعريفي المصدري",
      width: 496,
      height: 451,
    },
    capabilities: ["structural-design-shop-drawings"],
  },
  {
    slug: "al-sulaymaniyah-plaza",
    title: "بلازا السليمانية",
    shortTitle: "بلازا السليمانية",
    location: "حي السليمانية، جدة",
    sector: "تقييم",
    sectorSlug: "assessment",
    tier: "selected",
    sourcePage: 22,
    overview: "تطلب مبنى قائم فحصًا وتقوية للعناصر الإنشائية في الطوابق السفلية.",
    verifiedRole:
      "دعم الفحص والاختبار والتحليل حلاً لتقوية أعمدة الطوابق السفلية، شمل أعمال تسليح تحت الإشراف لمعالجة سلوك الثقب (Punching).",
    data: [
      { value: "60,000 sqm", label: "مساحة الأرض" },
      { value: "2", label: "عدد الطوابق" },
    ],
    parties: { owner: "Al Sulaiman Holding Group", contractor: "Essam Kabbani" },
    image: {
      src: "/projects/al-sulaymaniyah-plaza.webp",
      alt: "أعمال تقوية الطوابق السفلية في بلازا السليمانية",
      caption: "صورة المشروع / الملف التعريفي المصدري",
      width: 310,
      height: 231,
    },
    capabilities: ["value-engineering", "construction-management-supervision"],
  },

  // ------------------------------- EXTENDED — INFRASTRUCTURE & UTILITIES
  {
    slug: "national-guard-housing-bahra",
    title: "الإسكان بحرة للحرس الوطني",
    shortTitle: "الإسكان بحرة للحرس الوطني",
    location: "بحرة، جدة، المملكة العربية السعودية",
    sector: "سكني / بنية تحتية",
    sectorSlug: "infrastructure",
    tier: "extended",
    sourcePage: 25,
    overview:
      "مشروع إسكان لمنسوبي الحرس الوطني يضم 400 فيلا سكنية مع مرافق مساندة تشمل مدارس ومساجد، على مساحة إجمالية 800,000 متر مربع.",
    verifiedRole:
      "قُدِّمت مخططات تنفيذ تفصيلية لجميع شبكات البنية التحتية والمرافق، بما فيها إمداد المياه، ومياه الأمطار، والصرف الصحي، والري، والخطوط الكهربائية. وقدّم مكتب فني أُنشئ في الموقع خدمات التصميم الإنشائي وتقييم التصميم والتحقق منه، مع مخططات تفصيلية لمنشآت تشمل محطة معالجة الصرف الصحي، ومكاتب الحرس الوطني، والبوابة الرئيسية.",
    data: [
      { value: "400", label: "الفلل السكنية" },
      { value: "800,000 sqm", label: "مساحة الموقع" },
    ],
    parties: {
      owner: "Kingdom of Saudi Arabia National Guard",
      contractor: "Saudi Binladin Group",
      designer: "AAW Consultant & Maintenance Ltd. Co.",
      consultant: "Dar Al-Handasah (Shair and Partners)",
    },
    image: {
      src: "/projects/national-guard-bahra.webp",
      alt: "مشروع الإسكان بحرة التابع للحرس الوطني",
      caption: "صورة المشروع / الملف التعريفي المصدري",
      width: 531,
      height: 342,
    },
    capabilities: ["civil-infrastructure-surveying", "structural-design-shop-drawings"],
  },
  {
    slug: "al-faysaliyah-mixing-chamber",
    title: "غرفة خلط الفيصلية",
    shortTitle: "غرفة خلط الفيصلية",
    location: "جدة، المملكة العربية السعودية",
    sector: "البنية التحتية",
    sectorSlug: "infrastructure",
    tier: "extended",
    sourcePage: 26,
    overview: "تشكّل غرفة الخلط جزءًا من برنامج البنية التحتية المائية بالفيصلية.",
    verifiedRole:
      "قدّم مكتب فني في الموقع خدمات التصميم الإنشائي، والتحقق من التصميم، ومخططات تنفيذ تفصيلية، ومعلومات التنفيذ الفعلي، شملت أكثر من 1,000 مخطط وجدول وكمية.",
    data: [{ value: "1,000+", label: "المخططات" }],
    parties: {
      owner: "National Water Company",
      contractor: "Abuljadayel Contracting & Maintenance Ltd. Co.",
      consultant: "Saud Consult",
    },
    image: {
      src: "/projects/al-faysaliyah-mixing-chamber.webp",
      alt: "أعمال البنية التحتية لغرفة خلط الفيصلية",
      caption: "صورة المشروع / الملف التعريفي المصدري",
      width: 316,
      height: 361,
    },
    capabilities: ["civil-infrastructure-surveying", "structural-design-shop-drawings"],
  },
  {
    slug: "sawaco-project",
    title: "مشروع ساواكو",
    shortTitle: "مشروع ساواكو",
    location: "جنوب جدة، المملكة العربية السعودية",
    sector: "المساحة",
    sectorSlug: "surveying",
    tier: "extended",
    sourcePage: 27,
    overview: "موقع صناعي في جنوب جدة يضم مستودعات، ومبانٍ سكنية للعمال، ومرافق مصنعية.",
    verifiedRole:
      "سجّلت أعمال المسح الأرضي والطبوغرافي المباني والطرق والأعمال الخارجية والمرافق، مع إعداد معلومات كنتور منسّقة بأبعاد ثنائية وثلاثية.",
    data: [],
    parties: {
      owner: "Jeddah Chamber of Commerce",
      contractor: "Swidokiko_ME",
      consultant: "ZAK Engineering Consultants Company",
    },
    image: {
      src: "/projects/sawaco-project.webp",
      alt: "منطقة المسح للموقع الصناعي لمشروع ساواكو في جنوب جدة",
      caption: "صورة المشروع / الملف التعريفي المصدري",
      width: 725,
      height: 409,
    },
    capabilities: ["civil-infrastructure-surveying"],
  },

  // ------------------------------- EXTENDED — COMMERCIAL & HIGH-RISE
  {
    slug: "jameel-square-tahlia",
    title: "مبنى جميل سكوير — التحلية",
    shortTitle: "جميل سكوير — التحلية",
    location: "جدة، المملكة العربية السعودية",
    sector: "تجاري",
    sectorSlug: "commercial",
    tier: "extended",
    sourcePage: 29,
    overview: "مشروع تجاري في شارع التحلية بجدة.",
    verifiedRole:
      "دعمت هندسة القيمة الأداء الإنشائي وضبط التكلفة. وقُدِّمت نماذج تصميم الخرسانة المسلحة والصلب، والحسابات، ومخططات التنفيذ المنسّقة، ومستندات الكميات.",
    data: [],
    parties: {
      owner: "Mrs. Hadiah Abdullatif Jameel",
      contractor: "Ishada Contracting & Maintenance Ltd. Co.",
      consultant: "Saudi SOCOTEC",
    },
    image: {
      src: "/projects/jameel-square.webp",
      alt: "مبنى جميل سكوير التجاري في شارع التحلية بجدة",
      caption: "صورة المشروع / الملف التعريفي المصدري",
      width: 368,
      height: 251,
    },
    capabilities: ["value-engineering", "structural-design-shop-drawings"],
  },
  {
    slug: "twin-towers-bayat-plaza",
    title: "الأبراج التوأم — بايات بلازا",
    shortTitle: "الأبراج التوأم — بايات بلازا",
    location: "جدة، المملكة العربية السعودية",
    sector: "الأبراج العالية",
    sectorSlug: "high-rise",
    tier: "extended",
    sourcePage: 30,
    overview:
      "مجمّع مبانٍ عند تقاطع طريق المدينة وطريق الملك عبدالله في وسط جدة. ويتكوّن البرجان التوأم من مبنيين سكنيين يضمان طابقين سفليين، وطابقًا أرضيًا، وميزانين، وبرجًا من 24 طابقًا، وبرجًا من 33 طابقًا. أما برج BSTS متعدد الاستخدامات فيتكوّن من برج رئيسي من 43 طابقًا ومبنى مواقف من 10 طوابق.",
    verifiedRole: "مراجعة تصميم ودعم فني إنشائي.",
    data: [],
    parties: {
      owner: "Sabban Group",
      contractor: "Afrina Est. for Contracting",
      consultant: "Khoja Engineering Consultants",
    },
    capabilities: ["value-engineering", "construction-management-supervision"],
  },
  {
    slug: "al-rawda-building",
    title: "مبنى الروضة",
    shortTitle: "مبنى الروضة",
    location: "جدة، المملكة العربية السعودية",
    sector: "تجاري",
    sectorSlug: "commercial",
    tier: "extended",
    sourcePage: 31,
    overview:
      "مبنيان تجاريان في جدة، يتكوّن كل منهما من ثلاثة طوابق سفلية، وطابق أرضي، وميزانين، و12 طابقًا.",
    verifiedRole: "مخططات التصميم الإنشائي والاستشارات.",
    data: [],
    parties: {
      contractor: "OCC Weavers",
      consultant: "ZAK Engineering Consultants Company",
    },
    image: {
      src: "/projects/al-rawda-building.webp",
      alt: "مبنيا الروضة التجاريان في جدة",
      caption: "صورة المشروع / الملف التعريفي المصدري",
      width: 542,
      height: 346,
    },
    capabilities: ["structural-design-shop-drawings"],
  },
  {
    slug: "bayt-jameel-apartments",
    title: "شقق بيت جميل",
    shortTitle: "شقق بيت جميل",
    location: "جدة، المملكة العربية السعودية",
    sector: "سكني",
    sectorSlug: "residential",
    tier: "extended",
    sourcePage: 32,
    overview:
      "مجمّع شقق سكني في جدة بمساحة 80,000 متر مربع، يضم 11 عمارة بطابق سفلي وستة طوابق نموذجية.",
    verifiedRole: "التصميم، ومخططات التنفيذ، والدعم الفني الإنشائي.",
    data: [{ value: "80,000 sqm", label: "مساحة المجمع" }],
    parties: {
      owner: "ALJ Abdulateef Jameel Co. Ltd",
      contractor: "Rafic A Kreidia Engineering and Contractors",
      consultant: "Mohamad Harasani Consultants",
    },
    image: {
      src: "/projects/bayt-jameel-apartments.webp",
      alt: "مجمّع شقق بيت جميل السكني في جدة",
      caption: "صورة المشروع / الملف التعريفي المصدري",
      width: 698,
      height: 393,
    },
    capabilities: ["structural-design-shop-drawings", "construction-management-supervision"],
  },
  {
    slug: "al-shallal-towers",
    title: "أبراج الشلال",
    shortTitle: "أبراج الشلال",
    location: "جدة، المملكة العربية السعودية",
    sector: "الأبراج العالية",
    sectorSlug: "high-rise",
    tier: "extended",
    sourcePage: 33,
    overview: "مشروع أبراج عالية في جدة موثّق ضمن سجل المشاريع المتاح.",
    verifiedRole:
      "شمل النطاق المصدري التصميم الإنشائي والكهروميكانيكي، ومخططات التنفيذ الإنشائية، والدعم الفني الإنشائي، والإشراف.",
    data: [],
    parties: { owner: "Sheikh Tala'at Lami", consultant: "ZAK Engineering Consultants" },
    image: {
      src: "/projects/al-shallal-towers.webp",
      alt: "مشروع أبراج الشلال العالية في جدة",
      caption: "صورة المشروع / الملف التعريفي المصدري",
      width: 342,
      height: 368,
    },
    capabilities: ["structural-design-shop-drawings", "mep-bim-coordination"],
  },
  {
    slug: "sharbatly-cold-store",
    title: "مبردات الشربتلي والسكن",
    shortTitle: "مبردات الشربتلي",
    location: "الرياض، المملكة العربية السعودية",
    sector: "صناعي / سكني",
    sectorSlug: "industrial",
    tier: "extended",
    sourcePage: 34,
    overview: "مرافق تبريد وسكن طُوِّرت لصالح العميل.",
    verifiedRole:
      "نُسّقت نماذج التصميم الإنشائي والحسابات مع المتطلبات المعمارية والميكانيكية، إلى جانب مخططات التنفيذ وجداول تشكيل الحديد.",
    data: [],
    parties: {
      owner: "Mohamad A. Sharbatly Co. Ltd.",
      contractor: "OCC Weavers Ltd.",
      consultant: "KAOS",
    },
    capabilities: ["structural-design-shop-drawings"],
  },
  {
    slug: "al-rabeaa-tower",
    title: "برج الربيع",
    shortTitle: "برج الربيع",
    location: "طريق الملك عبدالعزيز، المدينة المنورة",
    sector: "تقييم",
    sectorSlug: "assessment",
    tier: "extended",
    sourcePage: 35,
    overview: "تطلّب برج قائم تقييمًا إنشائيًا وأعمال تقوية.",
    verifiedRole:
      "استرشدت إصلاحات الأساسات والأعمدة والكمرات بأخذ عينات خرسانية، واختبارات كيميائية، وتقييم غير إتلافي، باستخدام تكسية خرسانية وتطويق معدني.",
    data: [
      { value: "1,000 sqm", label: "مساحة الأرض" },
      { value: "17", label: "عدد الطوابق" },
    ],
    parties: {
      owner: "Al Ruwaished Real Estate Development Group",
      contractor: "Shahinco Company",
    },
    capabilities: ["value-engineering", "construction-management-supervision"],
  },
  {
    slug: "private-villa-khalidiya",
    title: "فيلا خاصة — الخالدية",
    shortTitle: "فيلا خاصة — الخالدية",
    location: "حي الخالدية، جدة",
    sector: "تقييم",
    sectorSlug: "assessment",
    tier: "extended",
    sourcePage: 36,
    overview: "مهمة تقوية لفيلا خاصة.",
    verifiedRole:
      "استرشدت أعمال تقوية الأساسات والأعمدة تحت الإشراف باستخدام أنظمة التكسية، بنتائج اختبار الخرسانة والمخططات الداعمة.",
    data: [
      { value: "1,500 sqm", label: "مساحة الأرض" },
      { value: "3", label: "عدد الطوابق" },
    ],
    parties: { owner: "Mohamed Saadi", contractor: "Rafiq Kareidi" },
    capabilities: ["value-engineering", "construction-management-supervision"],
  },

  // ------------------------------- EXTENDED — CONSTRUCTION SUPPORT
  {
    slug: "al-rofan-plaza",
    title: "بلازا الروفان",
    shortTitle: "بلازا الروفان",
    location: "حي الروضة، جدة",
    sector: "دعم إنشائي",
    sectorSlug: "commercial",
    tier: "extended",
    sourcePage: 38,
    overview:
      "مشروع تجاري وإداري بمساحة 25,000 متر مربع في حي الروضة بجدة، يتكوّن من ثلاثة طوابق سفلية و12 طابقًا علويًا تضم مكاتب ومطاعم ومواقف سيارات.",
    verifiedRole:
      "قُدِّمت مراجعة التصميم الإنشائي، والدعم الفني الإنشائي، وخدمات المساحة، إلى جانب الإشراف على المشروع.",
    data: [{ value: "25,000 sqm", label: "مساحة التطوير" }],
    parties: {
      owner: "Manafea Real Estate Holding Group",
      contractor: "United Construction Company for Contracting",
      consultant: "ZAK Engineering Consultants",
    },
    image: {
      src: "/projects/al-rofan-plaza.webp",
      alt: "مشروع بلازا الروفان التجاري والإداري",
      caption: "صورة المشروع / الملف التعريفي المصدري",
      width: 351,
      height: 654,
    },
    capabilities: ["construction-management-supervision", "civil-infrastructure-surveying"],
  },
  {
    slug: "al-twairki-10",
    title: "العُويرقي 10",
    shortTitle: "العُويرقي 10",
    location: "المملكة العربية السعودية",
    sector: "دعم إنشائي",
    sectorSlug: "hospitality",
    tier: "extended",
    sourcePage: 39,
    overview:
      "مبنى إداري وفندقي ومكتبي يخدم الزوّار، بمساحة إجمالية 50,000 متر مربع. ويتكوّن البرج متعدد الاستخدامات من طابق سفلي، وطابق أرضي، وميزانين، و24 طابقًا علويًا.",
    verifiedRole:
      "سُجِّل إشراف كامل وضبط جودة عبر مراحل التنفيذ، إلى جانب الاستشارة الإنشائية، ومراجعة التصميم، والدعم الفني الإنشائي.",
    data: [{ value: "50,000 sqm", label: "المساحة الإجمالية" }],
    parties: {
      owner: "Sheikh Marwan Al-Tuwairqi",
      contractor: "Saud Al Sa'adi Contracting Company",
      consultant: "ZAK Engineering Consultants",
    },
    capabilities: ["construction-management-supervision"],
  },
  {
    slug: "assila-twin-towers",
    title: "برجا الأصيلة التوأم",
    shortTitle: "برجا الأصيلة التوأم",
    location: "جدة، المملكة العربية السعودية",
    sector: "مراجعة التصميم",
    sectorSlug: "hospitality",
    tier: "extended",
    sourcePage: 40,
    overview: "مشروع ضيافة رئيسي ببرجين توأمين في جدة.",
    verifiedRole:
      "يوثّق النطاق المصدري المعتمد التحقق من التصميم الإنشائي ومراجعته وإعداد تقارير التصميم.",
    data: [],
    parties: {
      owner: "Mohammed Al Issa and Sons (MASC)",
      contractor: "Alsaad General Contracting Company",
      consultant: "Mohamad Harasani Architects",
    },
    image: {
      src: "/projects/assila-twin-towers.webp",
      alt: "مشروع برجي الأصيلة التوأم للضيافة في جدة",
      caption: "صورة المشروع / الملف التعريفي المصدري",
      width: 800,
      height: 550,
    },
    capabilities: ["value-engineering"],
  },
  {
    slug: "coral-palace",
    title: "قصر المرجان",
    shortTitle: "قصر المرجان",
    location: "حي المرجان، جدة",
    sector: "الضيافة",
    sectorSlug: "residential",
    tier: "extended",
    sourcePage: 41,
    overview:
      "مبنى سكني خاص بمساحة أرض 3,500 متر مربع في حي المرجان الراقي، بمساحة طابقية إجمالية 10,000 متر مربع.",
    verifiedRole:
      "إشراف إنشائي كامل وضبط جودة طوال مراحل التنفيذ، مع استشارة إنشائية، ومراجعة تصميم، ودعم فني إنشائي.",
    data: [{ value: "10,000 sqm", label: "المساحة الطابقية الإجمالية" }],
    parties: {
      owner: "Sheikh Hussein bin Muslim",
      contractor: "SBCM (Saudi Buildings and Construction Management)",
      consultant: "ZAK Engineering Consultants Company",
    },
    image: {
      src: "/projects/coral-palace.webp",
      alt: "قصر المرجان، المسكن الخاص في حي المرجان بجدة",
      caption: "صورة المشروع / الملف التعريفي المصدري",
      width: 390,
      height: 304,
    },
    capabilities: ["construction-management-supervision"],
  },
  {
    slug: "awtad-trading-center",
    title: "مركز أوتاد التجاري",
    shortTitle: "مركز أوتاد التجاري",
    location: "حي العزيزية، جدة",
    sector: "تجاري",
    sectorSlug: "commercial",
    tier: "extended",
    sourcePage: 42,
    overview:
      "يقع المشروع في شارع البلدية بحي العزيزية، أحد المناطق التجارية المهمة في جدة، وهو مبنى من 10 طوابق يضم محلات ومكاتب بمساحة إجمالية 16,000 متر مربع.",
    verifiedRole:
      "إشراف كامل وضبط جودة طوال مراحل التنفيذ، مع استشارة إنشائية، ومراجعة تصميم، ودعم فني إنشائي.",
    data: [{ value: "16,000 sqm", label: "المساحة الإجمالية" }],
    parties: {
      owner: "Awtad Company",
      contractor: "Riyad Hussein Saleh Contracting Est",
      consultant: "ZAK Engineering Consultants Company",
    },
    image: {
      src: "/projects/awtad-trading-center.webp",
      alt: "مبنى مركز أوتاد التجاري في جدة",
      caption: "صورة المشروع / الملف التعريفي المصدري",
      width: 572,
      height: 400,
    },
    capabilities: ["construction-management-supervision"],
  },
  {
    slug: "down-town-hotel",
    title: "فندق داون تاون",
    shortTitle: "فندق داون تاون",
    location: "جدة التاريخية، المملكة العربية السعودية",
    sector: "الضيافة",
    sectorSlug: "hospitality",
    tier: "extended",
    sourcePage: 43,
    overview:
      "مبنى فندقي من سبعة طوابق في منطقة جدة التاريخية، بطراز معماري مميز ومساحة إجمالية 3,500 متر مربع.",
    verifiedRole:
      "التصميم الإنشائي، والإشراف الكامل مع ضبط الجودة طوال مراحل التنفيذ، إلى جانب الاستشارة الإنشائية، ومراجعة التصميم، والدعم الفني الإنشائي.",
    data: [{ value: "3,500 sqm", label: "المساحة الإجمالية" }],
    parties: {
      owner: "Sheikh Saeed bin Othman AlAmoudi",
      contractor: "Riyad Hussein Saleh Contracting",
      consultant: "ZAK Engineering Consultants Company",
    },
    image: {
      src: "/projects/down-town-hotel.webp",
      alt: "فندق داون تاون في منطقة جدة التاريخية",
      caption: "صورة المشروع / الملف التعريفي المصدري",
      width: 590,
      height: 511,
    },
    capabilities: ["structural-design-shop-drawings", "construction-management-supervision"],
  },

  // ------------------------------- EXTENDED — ARCHITECTURE & INTERIORS
  {
    slug: "al-morjan-residence",
    title: "مسكن المرجان",
    shortTitle: "مسكن المرجان",
    location: "حي المرجان، جدة",
    sector: "العمارة / التصميم الداخلي",
    sectorSlug: "residential",
    tier: "extended",
    sourcePage: 45,
    overview: "تكليف سكني يضم فيلا رئيسية وفلل استراحة خاصة.",
    verifiedRole: "أُعدّت للتكليف مخططات معمارية، وتصميم داخلي، ومناظير ثلاثية الأبعاد.",
    data: [
      { value: "4,900 sqm", label: "مساحة الأرض" },
      { value: "كلاسيكي", label: "الطراز التصميمي" },
    ],
    parties: {
      contractor: "Riyad Hussin Saleh RHS",
      consultant: "ZAK Engineering Consultants Company",
    },
    image: {
      src: "/projects/al-morjan-residence.webp",
      alt: "منظور معماري لمسكن المرجان",
      caption: "صورة المشروع / الملف التعريفي المصدري",
      width: 679,
      height: 348,
    },
    capabilities: ["architecture-interior-design"],
  },
  {
    slug: "al-shatee-private-villa",
    title: "فيلا الشاطئ الخاصة",
    shortTitle: "فيلا الشاطئ الخاصة",
    location: "الشاطئ، جدة",
    sector: "العمارة / التصميم الداخلي",
    sectorSlug: "residential",
    tier: "extended",
    sourcePage: 48,
    overview:
      "مجمّع فلل من ثلاثة مبانٍ يضم فيلا رئيسية، وفيلا صغيرة، ومبنى ديوانية، تتخللها حدائق وممرات.",
    verifiedRole:
      "إعداد مخططات معمارية تفصيلية، وتصميم داخلي، ومخططات تنفيذية، ومخططات أثاث، مع مناظير مرئية مُصوَّرة.",
    data: [],
    parties: {
      contractor: "Riyad Hussin Saleh ASS",
      consultant: "ZAK Engineering Consultants Company",
    },
    image: {
      src: "/projects/al-shatee-private-villa.webp",
      alt: "منظور معماري لمجمّع فيلا الشاطئ الخاصة",
      caption: "صورة المشروع / الملف التعريفي المصدري",
      width: 700,
      height: 567,
    },
    capabilities: ["architecture-interior-design"],
  },
  {
    slug: "al-basateen-private-villas",
    title: "فلل البساتين الخاصة",
    shortTitle: "فلل البساتين الخاصة",
    location: "البساتين، جدة",
    sector: "العمارة / التصميم الداخلي",
    sectorSlug: "residential",
    tier: "extended",
    sourcePage: 49,
    overview:
      "خمس فلل من طابقين، ومبنى ديوانية، ومسبح مغطى، ومنطقة أنشطة خارجية، تتخللها مساحات خضراء وممرات.",
    verifiedRole:
      "إعداد مخططات معمارية تفصيلية، وتصميم داخلي، ومخططات تنفيذية، ومخططات أثاث، مع مناظير مرئية مُصوَّرة.",
    data: [],
    parties: {
      owner: "Private residence",
      contractor: "Riyad Hussein Saleh RHS",
      consultant: "ZAK Engineering Consultants Company",
    },
    image: {
      src: "/projects/al-basateen-private-villas.webp",
      alt: "منظور معماري لفلل البساتين الخاصة",
      caption: "صورة المشروع / الملف التعريفي المصدري",
      width: 970,
      height: 681,
    },
    capabilities: ["architecture-interior-design"],
  },

  // ------------------------------- EXTENDED — MEP & BIM
  {
    slug: "mall-of-saudi-office-building",
    title: "مول السعودية — المبنى الإداري",
    shortTitle: "مول السعودية — المبنى الإداري",
    location: "الرياض، المملكة العربية السعودية",
    sector: "متعدد التخصصات",
    sectorSlug: "commercial",
    tier: "extended",
    sourcePage: 51,
    overview:
      "تغطي المهمة حزمة المبنى الإداري ضمن مشروع مول السعودية في الرياض، بما يشمل المواقف والمناطق الفنية.",
    verifiedRole:
      "دعم مكتب فني المقاول الرئيسي لهذه الحزمة بمخططات ونماذج معمارية وإنشائية وكهربائية وتقنية معلومات وميكانيكية منسّقة.",
    data: [{ value: "30,000 sqm", label: "مساحة المهمة" }],
    parties: {
      owner: "Majid Al Futtaim",
      contractor: "MBL",
      leedConsultant: "AECOM",
      costManagement: "Turner & Townsend Arabia",
    },
    image: {
      src: "/projects/mall-of-saudi-office.webp",
      alt: "حزمة المبنى الإداري لمول السعودية في الرياض",
      caption: "صورة المشروع / الملف التعريفي المصدري",
      width: 510,
      height: 364,
    },
    capabilities: ["mep-bim-coordination", "structural-design-shop-drawings"],
  },
  {
    slug: "al-basateen-bin-dawood-compound",
    title: "فلل البساتين الخاصة — مجمّع بن داود",
    shortTitle: "مجمّع بن داود",
    location: "البساتين، جدة",
    sector: "متعدد التخصصات",
    sectorSlug: "residential",
    tier: "extended",
    sourcePage: 53,
    overview: "مجمّع سكني يضم تسع فلل، ومجلسًا مركزيًا، ومساحات ملحقة.",
    verifiedRole:
      "أُعدّت التصاميم ومخططات التنفيذ عبر الأنظمة المعمارية والإنشائية والكهربائية وتقنية المعلومات والميكانيكية.",
    data: [],
    parties: {
      owner: "Bin Dawood",
      contractor: "Riyad Hussein Saleh (RHS)",
      leedConsultant: "Mohamed Harasani Architects",
    },
    image: {
      src: "/projects/al-basateen-bin-dawood.webp",
      alt: "مجمّع بن داود السكني في البساتين",
      caption: "صورة المشروع / الملف التعريفي المصدري",
      width: 486,
      height: 387,
    },
    capabilities: ["mep-bim-coordination", "architecture-interior-design"],
  },
];
