import type { Project } from "../types";

/**
 * Project record. SOURCE: ZAK-Corporate-Profile-67P-Z3.2-DESIGN-LOCK.pdf.
 * `sourcePage` is the profile page each record was taken from.
 * Imagery is extracted from the same profile; projects without a rights-cleared
 * image in the source carry no `image` and render a typographic card instead.
 */
export const projects: Project[] = [
  // ---------------------------------------------------------------- FLAGSHIP
  {
    slug: "jeddah-tower",
    title: "Jeddah Tower",
    shortTitle: "Jeddah Tower",
    location: "Jeddah, Kingdom of Saudi Arabia",
    sector: "High-rise",
    sectorSlug: "high-rise",
    tier: "flagship",
    sourcePage: 11,
    overview:
      "Projected to rise over 1,000 metres, Jeddah Tower is planned as a 245,000 sqm mixed-use destination with offices, a 200-room Four Seasons Hotel, 121 serviced apartments and 360 residences.",
    verifiedRole:
      "Structural shop drawings and multidisciplinary coordination, including more than 6,000 drawings, structural design services, bar bending schedules, quantities, temporary structures and job-site engineering support.",
    data: [
      { value: "1,000+ m", label: "Projected height" },
      { value: "245,000 sqm", label: "Gross floor area" },
    ],
    parties: {
      owner: "Jeddah Economic City (JEC)",
      contractor: "Saudi Binladin Group / ABCD",
      consultant: "Dar Al-Handasah (Shair and Partners)",
    },
    image: {
      src: "/projects/jeddah-tower.webp",
      alt: "Jeddah Tower rendering showing the tapered supertall form above the surrounding waterfront development",
      caption: "Project rendering / source profile",
      width: 580,
      height: 820,
    },
    capabilities: ["structural-design-shop-drawings", "construction-management-supervision"],
  },
  {
    slug: "king-abdulaziz-international-airport",
    title: "King Abdulaziz International Airport",
    shortTitle: "King Abdulaziz Int'l Airport",
    location: "Jeddah, Kingdom of Saudi Arabia",
    sector: "Aviation",
    sectorSlug: "aviation",
    tier: "flagship",
    sourcePage: 12,
    overview:
      "The airport development comprises domestic, international and VIP facilities supported by 96 air bridges, with an initial planned capacity of approximately 30 million passengers.",
    verifiedRole:
      "On-site technical office, structural CAD standards, shop drawings and as-built documentation across terminals, load centres, multi-storey parking, and fire and rescue facilities.",
    data: [
      { value: "670,000 sqm", label: "Development area" },
      { value: "82", label: "Lounges" },
      { value: "30m passengers", label: "Phase 1 capacity" },
    ],
    parties: {
      owner: "General Authority of Civil Aviation (GACA)",
      contractor: "Saudi Binladin Group / ABCD",
      consultant: "Dar Al-Handasah Consulting Engineers",
    },
    image: {
      src: "/projects/kaia-terminal.webp",
      alt: "King Abdulaziz International Airport terminal building exterior",
      caption: "Airport overview / source profile",
      width: 699,
      height: 410,
    },
    capabilities: ["structural-design-shop-drawings", "construction-management-supervision"],
    relatedAssignment: {
      slug: "king-abdulaziz-international-airport-surveying",
      label: "Assignment B — Surveying / reality capture",
    },
  },
  {
    slug: "king-abdulaziz-international-airport-surveying",
    title: "King Abdulaziz International Airport — Surveying",
    shortTitle: "KAIA — Surveying",
    location: "Jeddah, Kingdom of Saudi Arabia",
    sector: "Aviation",
    sectorSlug: "aviation",
    tier: "flagship",
    sourcePage: 13,
    overview:
      "A surveying assignment within the King Abdulaziz International Airport project environment.",
    verifiedRole:
      "Topographic survey, contour generation and 3D scanning supported coordinated site information and spatial records.",
    data: [],
    parties: {
      owner: "General Authority of Civil Aviation (GACA)",
      contractor: "Saudi Binladin Group / ABCD",
      consultant: "Dar Al-Handasah Consulting Engineers",
    },
    image: {
      src: "/projects/kaia-surveying.webp",
      alt: "Survey and site record imagery from the King Abdulaziz International Airport environment",
      caption: "Project image / source profile",
      width: 637,
      height: 271,
    },
    capabilities: ["civil-infrastructure-surveying"],
    relatedAssignment: {
      slug: "king-abdulaziz-international-airport",
      label: "Assignment A — Technical office / structural delivery",
    },
  },
  {
    slug: "king-saud-university-endowment",
    title: "King Saud University Endowment Project",
    shortTitle: "KSU Endowment Project",
    location: "Riyadh, Kingdom of Saudi Arabia",
    sector: "Institutional / Mixed-use",
    sectorSlug: "institutional",
    tier: "flagship",
    sourcePage: 14,
    overview:
      "The project comprises eleven buildings and towers including a convention centre, shopping mall, luxury hotel, medical centre, hotel suites and office buildings, with an approximate built-up area of 680,000 sqm.",
    verifiedRole:
      "An engineering team worked with the contractor and project consultant to produce structural shop drawings.",
    data: [
      { value: "11", label: "Buildings & towers" },
      { value: "680,000 sqm", label: "Built-up area" },
    ],
    parties: {
      owner: "King Saud University — Business Sector",
      contractor: "Saudi Binladin Group / RPD",
      consultant: "Saudi Diyar Consults",
    },
    capabilities: ["structural-design-shop-drawings"],
  },
  {
    slug: "north-jeddah-wastewater-pumping-station",
    title: "North Jeddah Waste Water Pumping Station",
    shortTitle: "North Jeddah WWPS",
    location: "Jeddah, Kingdom of Saudi Arabia",
    sector: "Infrastructure",
    sectorSlug: "infrastructure",
    tier: "flagship",
    sourcePage: 15,
    overview:
      "A major wastewater development serving Jeddah includes pumping shafts approximately 40 m in diameter and 70 m deep, together with supporting buildings and site works.",
    verifiedRole:
      "A site technical office delivered structural and architectural design support, design evaluation, detailed shop drawings and as-built information. The assignment included more than 3,000 drawings, bar-bending schedules and quantities.",
    data: [{ value: "3,000+", label: "Drawings" }],
    parties: {
      owner: "National Water Company",
      contractor: "Abuljadayel Contracting & Maintenance Ltd. Co.",
      consultant: "Safege-P2mberlin Consortium",
    },
    image: {
      src: "/projects/north-jeddah-wwps.webp",
      alt: "North Jeddah waste water pumping station construction works",
      caption: "Project image / source profile",
      width: 470,
      height: 383,
    },
    capabilities: ["structural-design-shop-drawings", "civil-infrastructure-surveying"],
  },
  {
    slug: "almarai-cpp3",
    title: "Almarai CPP3 Central Processing Plant",
    shortTitle: "Almarai CPP3",
    location: "Al Kharj, Kingdom of Saudi Arabia",
    sector: "Industrial",
    sectorSlug: "industrial",
    tier: "flagship",
    sourcePage: 16,
    overview: "CPP3 is an industrial central processing plant developed for AlMarai.",
    verifiedRole:
      "Detailed reinforced-concrete and steel design models and calculation reports were coordinated with architectural and mechanical requirements, together with structural shop drawings and bar-bending schedules.",
    data: [],
    parties: { owner: "Almarai Company", contractor: "OCC Weavers Ltd." },
    image: {
      src: "/projects/almarai-cpp3.webp",
      alt: "Almarai CPP3 central processing plant facility",
      caption: "Project image / source profile",
      width: 674,
      height: 373,
    },
    capabilities: ["structural-design-shop-drawings"],
  },
  {
    slug: "fakeeh-madina-hospital",
    title: "Fakeeh Madina Hospital",
    shortTitle: "Fakeeh Madina Hospital",
    location: "Al Madinah Al Munawwarah, Kingdom of Saudi Arabia",
    sector: "Healthcare",
    sectorSlug: "healthcare",
    tier: "flagship",
    sourcePage: 17,
    overview:
      "A proposed conversion of an existing hotel structure into a hospital with approximately 65,000 sqm, 200 inpatient beds and specialist clinical facilities.",
    verifiedRole:
      "Independent multidisciplinary peer review assessed the re-design against engineering principles and standards across architecture, structure, electrical and mechanical packages.",
    data: [
      { value: "65,000 sqm", label: "Approximate area" },
      { value: "200", label: "Inpatient beds" },
    ],
    parties: {
      owner: "Dr. Soliman Fakeeh Hospital",
      designer: "DAR Engineering",
      consultant: "Z.A.K Engineering Consultants",
    },
    image: {
      src: "/projects/fakeeh-madina-hospital.webp",
      alt: "Fakeeh Madina Hospital building exterior",
      caption: "Project image / source profile",
      width: 955,
      height: 540,
    },
    capabilities: ["value-engineering", "mep-bim-coordination"],
  },

  // ---------------------------------------------------------------- SELECTED
  {
    slug: "hafez-building",
    title: "Hafez Building",
    shortTitle: "Hafez Building",
    location: "Jeddah, Kingdom of Saudi Arabia",
    sector: "Value engineering",
    sectorSlug: "commercial",
    tier: "selected",
    sourcePage: 18,
    overview: "A commercial building project in Jeddah.",
    verifiedRole:
      "Design review focused on structural value, supported by detailed shop drawings, inspection and quality control.",
    data: [],
    parties: {
      owner: "Diyarkom",
      contractor: "Ishada Contracting & Maintenance Ltd. Co.",
      consultant: "KAOS",
    },
    capabilities: ["value-engineering", "structural-design-shop-drawings"],
  },
  {
    slug: "alrassam-twin-towers",
    title: "AlRassam Twin Towers",
    shortTitle: "AlRassam Twin Towers",
    location: "Jeddah, Kingdom of Saudi Arabia",
    sector: "High-rise",
    sectorSlug: "high-rise",
    tier: "selected",
    sourcePage: 19,
    overview: "A twin-tower development supported through structural engineering delivery.",
    verifiedRole:
      "Value engineering, reinforced-concrete and steel design models, calculations, coordinated drawings and quantities were developed around function, reliability and cost control.",
    data: [],
    parties: {
      owner: "Mr. Saad AlRassam",
      contractor: "CPC Holding Company",
      consultant: "Buruoj Engineering Consultant",
    },
    image: {
      src: "/projects/alrassam-twin-towers.webp",
      alt: "AlRassam Twin Towers development",
      caption: "Project image / source profile",
      width: 317,
      height: 301,
    },
    capabilities: ["value-engineering", "structural-design-shop-drawings"],
  },
  {
    slug: "galleria-plaza",
    title: "Galleria Plaza",
    shortTitle: "Galleria Plaza",
    location: "Jeddah, Kingdom of Saudi Arabia",
    sector: "Mixed-use / Assessment",
    sectorSlug: "commercial",
    tier: "selected",
    sourcePage: 20,
    overview:
      "The source describes a Jeddah hospitality and retail development with more than 400 hotel rooms and a shopping mall.",
    verifiedRole:
      "In-situ structural surveying, deflection assessment and design review informed strengthening works to existing concrete slabs.",
    data: [
      { value: "400+", label: "Hotel rooms" },
      { value: "9,000 sqm", label: "Retail area" },
    ],
    parties: {
      owner: "SEDCO Holding",
      contractor: "United Constructors Contracting Company (UCCL)",
      consultant: "Kling Consult",
    },
    capabilities: ["value-engineering", "civil-infrastructure-surveying"],
  },
  {
    slug: "the-hotel-galleria",
    title: "The Hotel Galleria",
    shortTitle: "The Hotel Galleria",
    location: "Jeddah, Kingdom of Saudi Arabia",
    sector: "Mixed-use / Delivery",
    sectorSlug: "hospitality",
    tier: "selected",
    sourcePage: 21,
    overview:
      "The source describes a Jeddah hospitality and retail development with more than 400 hotel rooms and a shopping mall.",
    verifiedRole:
      "An engineering team supported the contractor and project consultant with structural shop drawings aligned to the project programme.",
    data: [
      { value: "400+", label: "Hotel rooms" },
      { value: "9,000 sqm", label: "Retail area" },
    ],
    parties: {
      owner: "SEDCO Holding",
      contractor: "United Constructors Contracting Company (UCCL)",
      consultant: "Kling Consult",
    },
    image: {
      src: "/projects/hotel-galleria.webp",
      alt: "The Hotel Galleria hospitality and retail development",
      caption: "Project image / source profile",
      width: 496,
      height: 451,
    },
    capabilities: ["structural-design-shop-drawings"],
  },
  {
    slug: "al-sulaymaniyah-plaza",
    title: "Al Sulaymaniyah Plaza",
    shortTitle: "Al Sulaymaniyah Plaza",
    location: "Sulaymaniyah District, Jeddah",
    sector: "Assessment",
    sectorSlug: "assessment",
    tier: "selected",
    sourcePage: 22,
    overview:
      "An existing building required investigation and strengthening of basement structural elements.",
    verifiedRole:
      "Assessment, testing and analysis supported a strengthening solution for basement columns, including supervised reinforcement works addressing punching behaviour.",
    data: [
      { value: "60,000 sqm", label: "Land area" },
      { value: "2", label: "Number of floors" },
    ],
    parties: { owner: "Al Sulaiman Holding Group", contractor: "Essam Kabbani" },
    image: {
      src: "/projects/al-sulaymaniyah-plaza.webp",
      alt: "Al Sulaymaniyah Plaza basement strengthening works",
      caption: "Project image / source profile",
      width: 310,
      height: 231,
    },
    capabilities: ["value-engineering", "construction-management-supervision"],
  },

  // ------------------------------- EXTENDED — INFRASTRUCTURE & UTILITIES
  {
    slug: "national-guard-housing-bahra",
    title: "National Guard Housing Bahra",
    shortTitle: "National Guard Housing Bahra",
    location: "Bahra, Jeddah, Kingdom of Saudi Arabia",
    sector: "Residential / Infrastructure",
    sectorSlug: "infrastructure",
    tier: "extended",
    sourcePage: 25,
    overview:
      "A housing development for National Guard personnel comprising 400 residential villas with supporting facilities including schools and mosques, on a total area of 800,000 sqm.",
    verifiedRole:
      "Detailed shop drawings were provided for all infrastructure networks and utilities, including water supply, storm water, sewage, irrigation and electrical lines. A technical office established on site provided structural design services, design evaluation and validation with detailed drawings for structures including the STP plant, SANG offices and main gate.",
    data: [
      { value: "400", label: "Residential villas" },
      { value: "800,000 sqm", label: "Site area" },
    ],
    parties: {
      owner: "Kingdom of Saudi Arabia National Guard",
      contractor: "Saudi Binladin Group",
      designer: "AAW Consultant & Maintenance Ltd. Co.",
      consultant: "Dar Al-Handasah (Shair and Partners)",
    },
    image: {
      src: "/projects/national-guard-bahra.webp",
      alt: "National Guard housing development at Bahra",
      caption: "Project image / source profile",
      width: 531,
      height: 342,
    },
    capabilities: ["civil-infrastructure-surveying", "structural-design-shop-drawings"],
  },
  {
    slug: "al-faysaliyah-mixing-chamber",
    title: "Al Faysaliyah Mixing Chamber",
    shortTitle: "Al Faysaliyah Mixing Chamber",
    location: "Jeddah, Kingdom of Saudi Arabia",
    sector: "Infrastructure",
    sectorSlug: "infrastructure",
    tier: "extended",
    sourcePage: 26,
    overview:
      "The mixing chamber forms part of the Al Faysaliyah water infrastructure programme.",
    verifiedRole:
      "A site technical office provided structural design services, design validation, detailed shop drawings and as-built information, including more than 1,000 drawings, schedules and quantities.",
    data: [{ value: "1,000+", label: "Drawings" }],
    parties: {
      owner: "National Water Company",
      contractor: "Abuljadayel Contracting & Maintenance Ltd. Co.",
      consultant: "Saud Consult",
    },
    image: {
      src: "/projects/al-faysaliyah-mixing-chamber.webp",
      alt: "Al Faysaliyah mixing chamber infrastructure works",
      caption: "Project image / source profile",
      width: 316,
      height: 361,
    },
    capabilities: ["civil-infrastructure-surveying", "structural-design-shop-drawings"],
  },
  {
    slug: "sawaco-project",
    title: "SAWACO Project",
    shortTitle: "SAWACO Project",
    location: "South Jeddah, Kingdom of Saudi Arabia",
    sector: "Surveying",
    sectorSlug: "surveying",
    tier: "extended",
    sourcePage: 27,
    overview:
      "An industrial site in south Jeddah containing warehouses, accommodation buildings and factory facilities.",
    verifiedRole:
      "Land and topographic surveys recorded buildings, roads, external works and utilities, with coordinated contour information prepared in 2D and 3D.",
    data: [],
    parties: {
      owner: "Jeddah Chamber of Commerce",
      contractor: "Swidokiko_ME",
      consultant: "ZAK Engineering Consultants Company",
    },
    image: {
      src: "/projects/sawaco-project.webp",
      alt: "SAWACO industrial site survey area in south Jeddah",
      caption: "Project image / source profile",
      width: 725,
      height: 409,
    },
    capabilities: ["civil-infrastructure-surveying"],
  },

  // ------------------------------- EXTENDED — COMMERCIAL & HIGH-RISE
  {
    slug: "jameel-square-tahlia",
    title: "Jameel Square Building — Tahlia",
    shortTitle: "Jameel Square — Tahlia",
    location: "Jeddah, Kingdom of Saudi Arabia",
    sector: "Commercial",
    sectorSlug: "commercial",
    tier: "extended",
    sourcePage: 29,
    overview: "A commercial development on Tahlia Street in Jeddah.",
    verifiedRole:
      "Value engineering supported structural performance and cost control. Reinforced-concrete and steel design models, calculations, coordinated shop drawings and quantity documentation were provided.",
    data: [],
    parties: {
      owner: "Mrs. Hadiah Abdullatif Jameel",
      contractor: "Ishada Contracting & Maintenance Ltd. Co.",
      consultant: "Saudi SOCOTEC",
    },
    image: {
      src: "/projects/jameel-square.webp",
      alt: "Jameel Square commercial building on Tahlia Street, Jeddah",
      caption: "Project image / source profile",
      width: 368,
      height: 251,
    },
    capabilities: ["value-engineering", "structural-design-shop-drawings"],
  },
  {
    slug: "twin-towers-bayat-plaza",
    title: "Twin Towers — Bayat Plaza",
    shortTitle: "Twin Towers — Bayat Plaza",
    location: "Jeddah, Kingdom of Saudi Arabia",
    sector: "High-rise",
    sectorSlug: "high-rise",
    tier: "extended",
    sourcePage: 30,
    overview:
      "A building complex at the intersection of Al Madina Road and King Abdullah Road in central Jeddah. The twin towers are two residential buildings comprising two basements, ground, mezzanine, a 24-floor tower and a 33-floor tower. The BSTS mixed-use tower comprises a 43-floor main tower and a 10-floor parking building.",
    verifiedRole: "Design review and construction technical support.",
    data: [],
    parties: {
      owner: "Sabban Group",
      contractor: "Afrina Est. for Contracting",
      consultant: "Khoja Engineering Consultants",
    },
    capabilities: ["value-engineering", "construction-management-supervision"],
  },
  {
    slug: "al-rawda-building",
    title: "Al Rawda Building",
    shortTitle: "Al Rawda Building",
    location: "Jeddah, Kingdom of Saudi Arabia",
    sector: "Commercial",
    sectorSlug: "commercial",
    tier: "extended",
    sourcePage: 31,
    overview:
      "Two commercial buildings located in Jeddah, each comprising three basements, ground floor, mezzanine and 12 floors.",
    verifiedRole: "Structural design drawings and consulting.",
    data: [],
    parties: {
      contractor: "OCC Weavers",
      consultant: "ZAK Engineering Consultants Company",
    },
    image: {
      src: "/projects/al-rawda-building.webp",
      alt: "Al Rawda commercial buildings in Jeddah",
      caption: "Project image / source profile",
      width: 542,
      height: 346,
    },
    capabilities: ["structural-design-shop-drawings"],
  },
  {
    slug: "bayt-jameel-apartments",
    title: "Bayt Jameel Apartments",
    shortTitle: "Bayt Jameel Apartments",
    location: "Jeddah, Kingdom of Saudi Arabia",
    sector: "Residential",
    sectorSlug: "residential",
    tier: "extended",
    sourcePage: 32,
    overview:
      "An 80,000 sqm apartment compound in Jeddah comprising 11 blocks with basement and six typical floors.",
    verifiedRole: "Design, shop drawings and construction technical support.",
    data: [{ value: "80,000 sqm", label: "Compound area" }],
    parties: {
      owner: "ALJ Abdulateef Jameel Co. Ltd",
      contractor: "Rafic A Kreidia Engineering and Contractors",
      consultant: "Mohamad Harasani Consultants",
    },
    image: {
      src: "/projects/bayt-jameel-apartments.webp",
      alt: "Bayt Jameel residential apartment compound in Jeddah",
      caption: "Project image / source profile",
      width: 698,
      height: 393,
    },
    capabilities: ["structural-design-shop-drawings", "construction-management-supervision"],
  },
  {
    slug: "al-shallal-towers",
    title: "Al Shallal Towers",
    shortTitle: "Al Shallal Towers",
    location: "Jeddah, Kingdom of Saudi Arabia",
    sector: "High-rise",
    sectorSlug: "high-rise",
    tier: "extended",
    sourcePage: 33,
    overview: "A high-rise development in Jeddah represented through the available project record.",
    verifiedRole:
      "Structural and electromechanical design, structural shop drawings, construction technical support and supervision were included in the source scope.",
    data: [],
    parties: { owner: "Sheikh Tala'at Lami", consultant: "ZAK Engineering Consultants" },
    image: {
      src: "/projects/al-shallal-towers.webp",
      alt: "Al Shallal Towers high-rise development in Jeddah",
      caption: "Project image / source profile",
      width: 342,
      height: 368,
    },
    capabilities: ["structural-design-shop-drawings", "mep-bim-coordination"],
  },
  {
    slug: "sharbatly-cold-store",
    title: "Sharbatly Cold Store & Accommodation",
    shortTitle: "Sharbatly Cold Store",
    location: "Riyadh, Kingdom of Saudi Arabia",
    sector: "Industrial / Residential",
    sectorSlug: "industrial",
    tier: "extended",
    sourcePage: 34,
    overview: "Cold-store and accommodation facilities developed for the client.",
    verifiedRole:
      "Structural design models and calculations were coordinated with architectural and mechanical requirements, together with shop drawings and bar-bending schedules.",
    data: [],
    parties: {
      owner: "Mohamad A. Sharbatly Co. Ltd.",
      contractor: "OCC Weavers Ltd.",
      consultant: "KAOS",
    },
    capabilities: ["structural-design-shop-drawings"],
  },
  {
    slug: "al-rabeaa-tower",
    title: "Al Rabeaa Tower",
    shortTitle: "Al Rabeaa Tower",
    location: "King Abdulaziz Road, Medina",
    sector: "Assessment",
    sectorSlug: "assessment",
    tier: "extended",
    sourcePage: 35,
    overview: "An existing tower required structural assessment and strengthening.",
    verifiedRole:
      "Concrete coring, chemical testing and non-destructive assessment informed repairs to foundations, columns and beams using concrete jacketing and metal confinement.",
    data: [
      { value: "1,000 sqm", label: "Land area" },
      { value: "17", label: "Number of floors" },
    ],
    parties: {
      owner: "Al Ruwaished Real Estate Development Group",
      contractor: "Shahinco Company",
    },
    capabilities: ["value-engineering", "construction-management-supervision"],
  },
  {
    slug: "private-villa-khalidiya",
    title: "Private Villa — Khalidiya",
    shortTitle: "Private Villa — Khalidiya",
    location: "Khalidiya District, Jeddah",
    sector: "Assessment",
    sectorSlug: "assessment",
    tier: "extended",
    sourcePage: 36,
    overview: "A private-villa strengthening assignment.",
    verifiedRole:
      "Concrete testing and supporting drawings informed supervised strengthening of foundations and columns using jacketing systems.",
    data: [
      { value: "1,500 sqm", label: "Land area" },
      { value: "3", label: "Number of floors" },
    ],
    parties: { owner: "Mohamed Saadi", contractor: "Rafiq Kareidi" },
    capabilities: ["value-engineering", "construction-management-supervision"],
  },

  // ------------------------------- EXTENDED — CONSTRUCTION SUPPORT
  {
    slug: "al-rofan-plaza",
    title: "Al Rofan Plaza",
    shortTitle: "Al Rofan Plaza",
    location: "Al Rawdah District, Jeddah",
    sector: "Construction support",
    sectorSlug: "commercial",
    tier: "extended",
    sourcePage: 38,
    overview:
      "A 25,000 sqm commercial and administrative development in Al Rawdah district, Jeddah, comprising three basement levels and 12 upper floors with offices, restaurants and parking.",
    verifiedRole:
      "Structural design review, construction technical support and surveying services were provided together with project supervision.",
    data: [{ value: "25,000 sqm", label: "Development area" }],
    parties: {
      owner: "Manafea Real Estate Holding Group",
      contractor: "United Construction Company for Contracting",
      consultant: "ZAK Engineering Consultants",
    },
    image: {
      src: "/projects/al-rofan-plaza.webp",
      alt: "Al Rofan Plaza commercial and administrative development",
      caption: "Project image / source profile",
      width: 351,
      height: 654,
    },
    capabilities: ["construction-management-supervision", "civil-infrastructure-surveying"],
  },
  {
    slug: "al-twairki-10",
    title: "Al Twairki 10",
    shortTitle: "Al Twairki 10",
    location: "Kingdom of Saudi Arabia",
    sector: "Construction support",
    sectorSlug: "hospitality",
    tier: "extended",
    sourcePage: 39,
    overview:
      "An administrative hotel and office building serving visitors, with a total area of 50,000 sqm. The mixed-use tower comprises basement, ground, mezzanine and 24 upper floors.",
    verifiedRole:
      "Full supervision and quality control were recorded across construction phases, together with structural consultation, design review and construction technical support.",
    data: [{ value: "50,000 sqm", label: "Total area" }],
    parties: {
      owner: "Sheikh Marwan Al-Tuwairqi",
      contractor: "Saud Al Sa'adi Contracting Company",
      consultant: "ZAK Engineering Consultants",
    },
    capabilities: ["construction-management-supervision"],
  },
  {
    slug: "assila-twin-towers",
    title: "The Assila Twin Towers",
    shortTitle: "Assila Twin Towers",
    location: "Jeddah, Kingdom of Saudi Arabia",
    sector: "Design review",
    sectorSlug: "hospitality",
    tier: "extended",
    sourcePage: 40,
    overview: "A major twin-tower hospitality development in Jeddah.",
    verifiedRole:
      "The verified source scope records structural design validation, review and design reporting.",
    data: [],
    parties: {
      owner: "Mohammed Al Issa and Sons (MASC)",
      contractor: "Alsaad General Contracting Company",
      consultant: "Mohamad Harasani Architects",
    },
    image: {
      src: "/projects/assila-twin-towers.webp",
      alt: "The Assila Twin Towers hospitality development in Jeddah",
      caption: "Project image / source profile",
      width: 800,
      height: 550,
    },
    capabilities: ["value-engineering"],
  },
  {
    slug: "coral-palace",
    title: "Coral Palace",
    shortTitle: "Coral Palace",
    location: "Al Marjan District, Jeddah",
    sector: "Hospitality",
    sectorSlug: "residential",
    tier: "extended",
    sourcePage: 41,
    overview:
      "A 3,500 sqm private residence building located in the upscale Coral District, with a total floor area of 10,000 sqm.",
    verifiedRole:
      "Structural full supervision and quality control throughout construction phases, with structural consultation, design review and construction technical support.",
    data: [{ value: "10,000 sqm", label: "Total floor area" }],
    parties: {
      owner: "Sheikh Hussein bin Muslim",
      contractor: "SBCM (Saudi Buildings and Construction Management)",
      consultant: "ZAK Engineering Consultants Company",
    },
    image: {
      src: "/projects/coral-palace.webp",
      alt: "Coral Palace private residence in the Al Marjan district of Jeddah",
      caption: "Project image / source profile",
      width: 390,
      height: 304,
    },
    capabilities: ["construction-management-supervision"],
  },
  {
    slug: "awtad-trading-center",
    title: "Awtad Trading Center",
    shortTitle: "Awtad Trading Center",
    location: "Al Aziziyah District, Jeddah",
    sector: "Commercial",
    sectorSlug: "commercial",
    tier: "extended",
    sourcePage: 42,
    overview:
      "Located on Al-Baladiah Street in Al Aziziyah District, one of Jeddah's important commercial areas, the project is a 10-storey building of shops and offices with a total area of 16,000 sqm.",
    verifiedRole:
      "Full supervision and quality control throughout construction phases, with structural consultancy, design review and construction technical support.",
    data: [{ value: "16,000 sqm", label: "Total area" }],
    parties: {
      owner: "Awtad Company",
      contractor: "Riyad Hussein Saleh Contracting Est",
      consultant: "ZAK Engineering Consultants Company",
    },
    image: {
      src: "/projects/awtad-trading-center.webp",
      alt: "Awtad Trading Center commercial building in Jeddah",
      caption: "Project image / source profile",
      width: 572,
      height: 400,
    },
    capabilities: ["construction-management-supervision"],
  },
  {
    slug: "down-town-hotel",
    title: "Down Town Hotel",
    shortTitle: "Down Town Hotel",
    location: "Historic Jeddah, Kingdom of Saudi Arabia",
    sector: "Hospitality",
    sectorSlug: "hospitality",
    tier: "extended",
    sourcePage: 43,
    overview:
      "A seven-storey hotel building in the historic area of Jeddah with a distinctive architecture and a total area of 3,500 sqm.",
    verifiedRole:
      "Structural design and full supervision with quality control throughout construction phases, together with structural consultation, design review and construction technical support.",
    data: [{ value: "3,500 sqm", label: "Total area" }],
    parties: {
      owner: "Sheikh Saeed bin Othman AlAmoudi",
      contractor: "Riyad Hussein Saleh Contracting",
      consultant: "ZAK Engineering Consultants Company",
    },
    image: {
      src: "/projects/down-town-hotel.webp",
      alt: "Down Town Hotel in the historic area of Jeddah",
      caption: "Project image / source profile",
      width: 590,
      height: 511,
    },
    capabilities: ["structural-design-shop-drawings", "construction-management-supervision"],
  },

  // ------------------------------- EXTENDED — ARCHITECTURE & INTERIORS
  {
    slug: "al-morjan-residence",
    title: "Al Morjan Residence",
    shortTitle: "Al Morjan Residence",
    location: "Al Morjan Neighbourhood, Jeddah",
    sector: "Architecture / Interiors",
    sectorSlug: "residential",
    tier: "extended",
    sourcePage: 45,
    overview: "A residential commission comprising a main villa and private camp villas.",
    verifiedRole:
      "Architectural drawings, interior design and 3D perspectives were produced for the commission.",
    data: [
      { value: "4,900 sqm", label: "Land area" },
      { value: "Classic", label: "Design style" },
    ],
    parties: {
      contractor: "Riyad Hussin Saleh RHS",
      consultant: "ZAK Engineering Consultants Company",
    },
    image: {
      src: "/projects/al-morjan-residence.webp",
      alt: "Al Morjan Residence architectural perspective",
      caption: "Project image / source profile",
      width: 679,
      height: 348,
    },
    capabilities: ["architecture-interior-design"],
  },
  {
    slug: "al-shatee-private-villa",
    title: "Al Shatee Private Villa",
    shortTitle: "Al Shatee Private Villa",
    location: "Al Shatee, Jeddah",
    sector: "Architecture / Interiors",
    sectorSlug: "residential",
    tier: "extended",
    sourcePage: 48,
    overview:
      "A three-building villa complex comprising a main villa, small villa and Dewaniya building, interspersed by gardens and walkways.",
    verifiedRole:
      "Production of detailed architectural drawings, interior design, executive drawings and furniture drawings with rendered perspectives.",
    data: [],
    parties: {
      contractor: "Riyad Hussin Saleh ASS",
      consultant: "ZAK Engineering Consultants Company",
    },
    image: {
      src: "/projects/al-shatee-private-villa.webp",
      alt: "Al Shatee private villa complex architectural perspective",
      caption: "Project image / source profile",
      width: 700,
      height: 567,
    },
    capabilities: ["architecture-interior-design"],
  },
  {
    slug: "al-basateen-private-villas",
    title: "Al Basateen Private Villas",
    shortTitle: "Al Basateen Private Villas",
    location: "Al Basateen, Jeddah",
    sector: "Architecture / Interiors",
    sectorSlug: "residential",
    tier: "extended",
    sourcePage: 49,
    overview:
      "Five two-floor villas, a Dewaniya building, an enclosed swimming pool and outdoor activities area interspersed by landscape and walkways.",
    verifiedRole:
      "Production of detailed architectural drawings, interior design, executive drawings and furniture drawings with rendered perspectives.",
    data: [],
    parties: {
      owner: "Private residence",
      contractor: "Riyad Hussein Saleh RHS",
      consultant: "ZAK Engineering Consultants Company",
    },
    image: {
      src: "/projects/al-basateen-private-villas.webp",
      alt: "Al Basateen private villas architectural perspective",
      caption: "Project image / source profile",
      width: 970,
      height: 681,
    },
    capabilities: ["architecture-interior-design"],
  },

  // ------------------------------- EXTENDED — MEP & BIM
  {
    slug: "mall-of-saudi-office-building",
    title: "Mall of Saudi — Office Building",
    shortTitle: "Mall of Saudi — Office Building",
    location: "Riyadh, Kingdom of Saudi Arabia",
    sector: "Multidisciplinary",
    sectorSlug: "commercial",
    tier: "extended",
    sourcePage: 51,
    overview:
      "The assignment covers an office-building package within the Mall of Saudi development in Riyadh, including parking and technical areas.",
    verifiedRole:
      "A technical office supported the main contractor for this package with coordinated architectural, structural, electrical, ICT and mechanical drawings and models.",
    data: [{ value: "30,000 sqm", label: "Assignment area" }],
    parties: {
      owner: "Majid Al Futtaim",
      contractor: "MBL",
      leedConsultant: "AECOM",
      costManagement: "Turner & Townsend Arabia",
    },
    image: {
      src: "/projects/mall-of-saudi-office.webp",
      alt: "Mall of Saudi office building package in Riyadh",
      caption: "Project image / source profile",
      width: 510,
      height: 364,
    },
    capabilities: ["mep-bim-coordination", "structural-design-shop-drawings"],
  },
  {
    slug: "al-basateen-bin-dawood-compound",
    title: "Al Basateen Private Villas — Bin Dawood Compound",
    shortTitle: "Bin Dawood Compound",
    location: "Al Basateen, Jeddah",
    sector: "Multidisciplinary",
    sectorSlug: "residential",
    tier: "extended",
    sourcePage: 53,
    overview:
      "A residential compound comprising nine villas, a central majlis and associated spaces.",
    verifiedRole:
      "Design and shop drawings were produced across architectural, structural, electrical, ICT and mechanical systems.",
    data: [],
    parties: {
      owner: "Bin Dawood",
      contractor: "Riyad Hussein Saleh (RHS)",
      leedConsultant: "Mohamed Harasani Architects",
    },
    image: {
      src: "/projects/al-basateen-bin-dawood.webp",
      alt: "Bin Dawood residential compound at Al Basateen",
      caption: "Project image / source profile",
      width: 486,
      height: 387,
    },
    capabilities: ["mep-bim-coordination", "architecture-interior-design"],
  },
];
